name: Release

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  releases:
    name: Build and Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      # Menggunakan sintaks baru $GITHUB_OUTPUT
      - name: Get version from pubspec.yaml
        id: version
        run: echo "version=$(grep 'version:' pubspec.yaml | cut -c10-)" >> $GITHUB_OUTPUT

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Get packages
        run: flutter pub get

      # Langkah krusial yang memperbaiki error sebelumnya
      - name: Create Keystore & Properties
        run: |
          # 1. Decode Keystore
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks
          
          # 2. Buat key.properties
          # Kita samakan path-nya dengan setup lokal agar aman (storeFile langsung nama file)
          echo "storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - name: Build APK
        run: flutter build apk --split-per-abi

      - name: Get current date
        id: date
        run: echo "date=$(TZ='Asia/Jakarta' date +'%A %d-%m-%Y %T WIB')" >> $GITHUB_OUTPUT

      - name: Generate unique tag
        id: tag
        run: echo "tag=v${{ steps.version.outputs.version }}-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Release APK
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: false
          # Upload semua APK hasil split (arm64-v8a, armeabi-v7a, x86_64)
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          body: "Published at ${{ steps.date.outputs.date }}"
          name: "v${{ steps.version.outputs.version }} - ${{ steps.date.outputs.date }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.tag.outputs.tag }}